server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://k8s-demo-mysql-service:3305/k8s_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root1234
  mvc:
    favicon:
      enabled: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .ftl
    mode: HTML5
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


#thymeleaf
#默认到resource/templates目录下寻找

